### ISSUE TITLE
Review Governance process

### ISSUE THREAD

**Issue by swinslow** [swinslow/slsa-governance#4]
The [Governance Policy](https://github.com/swinslow/slsa-governance/blob/main/5._Governance.md) defines the practical specifics of how the Working Group members will work together to draft, review and approve specifications, as well as some details around decision-making processes.

I'd encourage the community to review this Governance Policy carefully and confirm whether it fits with how they plan to work together. Most parts of this can be flexible to fit with the community's desired processes (though I would not recommend modifying the principles in section 3, "Ways of Working"). If the community has no strong opinions then you can stick with this default policy, but I'd recommend reviewing it and discussing / proposing changes if desired.

**Comment by kimsterv** [comment]
SLSA is a project under a WG and has its own steering committee. We need to align SLSAs current governance with this newly proposed one. Here is one of the [early docs](https://docs.google.com/document/d/1RUBpf2Hjy-yjP8x2rZ9hxT4LzlrpX45hmTO_RAFLrcg/edit) we used on SLSA governance. I think there's documentation somewhere about the structure of the steering committee. I'll see if I can dig it up. It might just be documented in the regular meeting notes.

**Comment by joshuagl** [comment]
I like how the governance proposal here suggests we formally document maintainers and editors (we have folks who fill those roles today, I think, but are not documented as such).

In addition we should keep the multi-company rotating members steering committee concept, which isn't captured in the current proposal here. 

Initial discussion of the steering committee was in the [2021-08-11 SLSA community meeting](https://docs.google.com/document/d/1cx3fOBfic6A0xc2on25ITK4vQHUdxgBmJoSS1LPqDJo/edit#heading=h.on2gem9934f8) and copy/pasted here:

> Governance / maintainers [15-30 min?]
> * Current draft: [SLSA Governance](https://docs.google.com/document/d/1RUBpf2Hjy-yjP8x2rZ9hxT4LzlrpX45hmTO_RAFLrcg/edit) (NOW PUBLIC!)
> * Important to have multiple organization representation - anything major should require multiple organizations to agree.
> * 3 months before ejecting is really short - increase to 12 months? 6 months? Or just stay on until vote off?
> * What happens if this becomes less active? Keep the “last 3 maintainers” stay on? Otherwise you could have a case where 0 people are authorized to make changes :-).
> * Would a steering committee make sense?
>   * Yes, perhaps a subset of maintainers for arbitration. Best if there are multiple organizations in the steering committee.
>   * Could also appeal to the OpenSSF TAC as a steering committee to appeal to
> * Tiered approach, simple clarifications require +1, breaking changes requires agreement and cooldown period
> Need process for getting consensus, e.g. [#127](https://github.com/slsa-framework/slsa/issues/127) which generates a lot of discussion but hard to get consensus on GitHub Issues
> * Interest in steering committee (currently 7 members, will shrink to 5 based on contributions): 
>   * Bruno Domingues (Intel)
>   * David A. Wheeler (Linux Foundation)
>   * Joshua Lock (VMware)
>   * Mark Lodato (Google)
>   * Mike Lieberman (Citi/CNCF)
>   * Trishank Karthik Kuppusamy (Datadog/TUF/in-toto)
>   * Zak Greant (ActiveState) – Also interested in outreach to FLOSS projects that may want to implement SLSA, so that we can get a broader perspective. eg. PHP has faced supply chain problems - is the PHP group wanting to improve their processes further with SLSA as a reference point?
>   * Want different organizations
>   * The expectation is that they’ll rotate
> * Want more than 3 in case someone goes on vacation, 5 (or 7) is better
> * Could use Tekton as a reference, has something very similar already ([bootstrap](https://github.com/tektoncd/community/blob/e9b456c9e26515441680bbce7f746be55694b76b/governance.md), [today's state](https://github.com/tektoncd/community/blob/main/governance.md))

**Comment by kimsterv** [comment]
Thanks Joshua for digging this up and +1!

I replaced Zak on the steering committee and that’s documented too.

**Comment by joshuagl** [comment]
Yep. Kim replacing Zak was actioned here https://github.com/slsa-framework/slsa/pull/283

**Comment by swinslow** [comment]
Added a variety of changes in #5 -- closing this issue, and will flag the full repo for review / +1's to transfer over.
